package com.vayunmathur.findfamily.tracker

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Pure-JVM tests for the powered-off EID scheme.
 *
 * These matter more than most: the beacon half arms the Bluetooth controller from
 * [PoweredOffProtocol.armingEids] and the finder half looks reports up by
 * [PoweredOffProtocol.handleOf], and if the two ever disagree the feature fails with no error at
 * all — no crash, no log, just zero sightings forever. A golden vector is the only thing that
 * catches a silent change to the derivation.
 */
class PoweredOffProtocolTest {

    private val secret = ByteArray(32) { it.toByte() }

    @Test
    fun eidIsTwentyBytesAndDeterministic() {
        val a = PoweredOffProtocol.eid(secret, 1)
        val b = PoweredOffProtocol.eid(secret, 1)
        // Not negotiable: Eid.aidl is byte[20] and the vendor HCI command copies exactly 20.
        assertEquals(20, a.size)
        assertEquals(PoweredOffProtocol.EID_LEN, a.size)
        assertTrue(a.contentEquals(b), "same (secret, slot) -> same EID")
    }

    @Test
    fun eidRotatesWithSlotAndSecret() {
        val a = PoweredOffProtocol.eid(secret, 1)
        assertFalse(a.contentEquals(PoweredOffProtocol.eid(secret, 2)), "different slot -> different EID")
        val other = ByteArray(32) { (it + 1).toByte() }
        assertFalse(a.contentEquals(PoweredOffProtocol.eid(other, 1)), "different secret -> different EID")
    }

    @Test
    fun eidMatchesFixedVectors() {
        // Generated by an independent HMAC-SHA256 implementation over
        // "ffpof1" || u64_be(slot) with secret = 00 01 02 ... 1f, truncated to 20 bytes.
        // The beacon half must produce exactly these bytes for these inputs.
        assertEquals(
            "2b3e6577a94b55fc2232abba76d7877ab4bbfbc9",
            PoweredOffProtocol.eid(secret, 0).toHex()
        )
        assertEquals(
            "a9969ffba4d4f4e7a50ed4c45ee11bf5d48d8a3b",
            PoweredOffProtocol.eid(secret, 1).toHex()
        )
        assertEquals(
            "6a3937ce919087a7bb26d23bb39080ef9ef54042",
            PoweredOffProtocol.eid(secret, 1_660_156).toHex()
        )
    }

    @Test
    fun eidIsDistinctFromTheTrackerEpochIdSpace() {
        // Different domain tag, so a powered-off EID can never be mistaken for a live tracker's
        // beacon id even though both are HMACs of the same secret.
        val eidPrefix = PoweredOffProtocol.handleOf(PoweredOffProtocol.eid(secret, 5))
        assertFalse(
            eidPrefix.contentEquals(TrackerProtocol.epochId(secret, 5)),
            "domain separation must hold"
        )
    }

    @Test
    fun handleIsTheFirstSixteenBytes() {
        val eid = PoweredOffProtocol.eid(secret, 7)
        val handle = PoweredOffProtocol.handleOf(eid)
        // The relay's resolve and report frames are 16 bytes wide; widening them was avoidable.
        assertEquals(TrackerProtocol.EPOCH_ID_LEN, handle.size)
        assertTrue(handle.contentEquals(eid.copyOf(16)))
    }

    @Test
    fun slotPeriodMatchesTheHalConstant() {
        // kPrecomputedKeyRotatedInterval = 0x400 in bluetooth_finder_handler.cc. Changing this
        // desynchronises us from the controller's own rotation timer.
        assertEquals(1024L, PoweredOffProtocol.SLOT_SECONDS)
        val nowMs = 1_788_811_451_000L
        assertEquals(1_746_886L, PoweredOffProtocol.currentSlot(nowMs))
    }

    @Test
    fun armingEidsStartAtTheShutdownSlotAndRunForward() {
        val nowMs = 1_788_811_451_000L
        val eids = PoweredOffProtocol.armingEids(secret, nowMs = nowMs, count = 4)
        val first = PoweredOffProtocol.currentSlot(nowMs)
        assertEquals(4, eids.size)
        // The controller starts on index 0 and advances forwards, so index 0 must be the slot the
        // device shut down in, not a past one.
        eids.forEachIndexed { i, e ->
            assertTrue(e.contentEquals(PoweredOffProtocol.eid(secret, first + i)), "index $i")
        }
    }

    @Test
    fun recentHandlesCoverTheArmedWindowAndOneSlotAhead() {
        val nowMs = 1_788_811_451_000L
        val handles = PoweredOffProtocol.recentHandles(secret, nowMs = nowMs, back = 3)
        val cur = PoweredOffProtocol.currentSlot(nowMs)
        // One ahead (for a beacon armed by a slightly fast clock) plus the current slot plus 3 back.
        assertEquals(5, handles.size)
        assertTrue(handles[0].contentEquals(PoweredOffProtocol.handleOf(PoweredOffProtocol.eid(secret, cur + 1))))
        assertTrue(handles[1].contentEquals(PoweredOffProtocol.handleOf(PoweredOffProtocol.eid(secret, cur))))
        assertTrue(handles[4].contentEquals(PoweredOffProtocol.handleOf(PoweredOffProtocol.eid(secret, cur - 3))))
    }

    @Test
    fun armedWindowFillsTheControllersKeyIndex() {
        // The key index is one byte on the wire (command[5] / command[10] in
        // bluetooth_finder_handler.cc), so 256 keys (index 0..255) is everything the controller
        // can address. There is no reason to arm fewer.
        assertEquals(256, PoweredOffProtocol.ARMED_SLOTS)
        // 256 * 1024s = 72.8 hours, a little over three days of powered-off advertising.
        assertEquals(262_144L, PoweredOffProtocol.ARMED_SLOTS * PoweredOffProtocol.SLOT_SECONDS)
    }

    @Test
    fun armingEidsDefaultsToTheWholeWindowAndIsAllDistinct() {
        val eids = PoweredOffProtocol.armingEids(secret, nowMs = 1_788_811_451_000L)
        assertEquals(PoweredOffProtocol.ARMED_SLOTS, eids.size)
        // A repeat would mean the beacon reuses an identifier, which is exactly the
        // trackable-static-id failure the rotation exists to avoid.
        assertEquals(eids.size, eids.map { it.toHex() }.toSet().size)
    }

    private fun ByteArray.toHex() = joinToString("") { "%02x".format(it) }
}
