package com.vayunmathur.findfamily.tracker

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Pure-JVM tests for the derived UWB session material.
 *
 * The fixed vectors matter more than the property assertions: the tracker firmware
 * recomputes these with PSA-Crypto HKDF, and if the two implementations disagree by a
 * byte the FiRa session simply never converges, with no error to point at the cause.
 * They were generated by an independent HKDF-SHA256 implementation.
 */
class TrackerUwbKeysTest {

    private val secret = ByteArray(32) { it.toByte() }

    private fun hex(b: ByteArray) = b.joinToString("") { "%02x".format(it) }

    @Test
    fun stsKeyMatchesFixedVector() {
        assertEquals("d1a3d794d6914e30", hex(TrackerUwbKeys.stsKey(secret, 0x01020304)))
        assertEquals("920bcfae670059c2", hex(TrackerUwbKeys.stsKey(secret, 0)))
    }

    @Test
    fun stsKeyIsEightBytesAndDeterministic() {
        val a = TrackerUwbKeys.stsKey(secret, 42)
        assertEquals(TrackerUwbKeys.STS_KEY_LEN, a.size)
        assertTrue(a.contentEquals(TrackerUwbKeys.stsKey(secret, 42)), "same (secret, sessionId) -> same key")
    }

    @Test
    fun stsKeyVariesWithSessionIdAndSecret() {
        val a = TrackerUwbKeys.stsKey(secret, 42)
        assertFalse(a.contentEquals(TrackerUwbKeys.stsKey(secret, 43)), "different sessionId -> different key")
        val other = ByteArray(32) { (it + 1).toByte() }
        assertFalse(a.contentEquals(TrackerUwbKeys.stsKey(other, 42)), "different secret -> different key")
    }

    @Test
    fun uwbAddressMatchesFixedVector() {
        assertEquals("1eef", hex(TrackerUwbKeys.uwbAddress(secret)))
    }

    @Test
    fun uwbAddressIsTwoBytesAndNeverReserved() {
        // 0x0000 and 0xFFFF are reserved by FiRa. The derivation can't be steered, so
        // sweep a range of secrets and assert the guard holds for whatever comes out.
        for (i in 0 until 512) {
            val s = ByteArray(32) { (it + i).toByte() }
            val addr = TrackerUwbKeys.uwbAddress(s)
            assertEquals(2, addr.size)
            assertFalse(addr[0] == 0x00.toByte() && addr[1] == 0x00.toByte(), "0x0000 is reserved")
            assertFalse(addr[0] == 0xFF.toByte() && addr[1] == 0xFF.toByte(), "0xFFFF is reserved")
        }
    }

    @Test
    fun derivationsRejectWrongSizedSecrets() {
        val short = ByteArray(16)
        assertFalse(runCatching { TrackerUwbKeys.stsKey(short, 1) }.isSuccess)
        assertFalse(runCatching { TrackerUwbKeys.uwbAddress(short) }.isSuccess)
    }

    @Test
    fun stsKeyAndAddressAreDomainSeparated() {
        // Same secret, same HKDF — only the info string differs. A copy-paste slip in
        // either info string would show up as one being a prefix of the other.
        val sts = TrackerUwbKeys.stsKey(secret, 0)
        val addr = TrackerUwbKeys.uwbAddress(secret)
        assertFalse(sts.copyOf(2).contentEquals(addr), "sts key and address must not share a derivation")
    }
}
