package com.vayunmathur.launcher.domain

/**
 * Where an item lives.
 *
 * Persisted as a single `Long` using Launcher3's sentinel scheme (see [toRaw]) because
 * one column keeps every placement query type-agnostic, and drag-and-drop routinely
 * moves an item between the three kinds of container. This sealed type exists so no
 * code above the DAO ever handles the magic numbers.
 */
sealed interface ContainerRef {
    /** The paged home screen. Items also carry a `screen` (page) index. */
    data object Desktop : ContainerRef

    /** The fixed row at the bottom, present on every page. `screen` is unused. */
    data object Hotseat : ContainerRef

    /** Inside the folder with this row id. `screen` is unused; `rank` orders children. */
    data class Folder(val id: Long) : ContainerRef
}

/** Sentinel container ids. Negative, so they cannot collide with an autogenerated row id. */
const val CONTAINER_DESKTOP = -100L
const val CONTAINER_HOTSEAT = -101L

fun ContainerRef.toRaw(): Long = when (this) {
    ContainerRef.Desktop -> CONTAINER_DESKTOP
    ContainerRef.Hotseat -> CONTAINER_HOTSEAT
    is ContainerRef.Folder -> id
}

fun containerRefOf(raw: Long): ContainerRef = when (raw) {
    CONTAINER_DESKTOP -> ContainerRef.Desktop
    CONTAINER_HOTSEAT -> ContainerRef.Hotseat
    else -> ContainerRef.Folder(raw)
}
