package com.vayunmathur.photos.data

import androidx.room.Dao
import androidx.room.Entity
import androidx.room.Index
import androidx.room.Insert
import androidx.room.PrimaryKey
import androidx.room.Query
import androidx.room.Update
import kotlinx.coroutines.flow.Flow

/**
 * One person discovered by on-device face clustering. Faces whose embeddings are
 * close enough (cosine similarity, see
 * [com.vayunmathur.photos.util.FaceRecognizer]) share a [Person] — a cluster is
 * "the same face seen across photos", found without any supervision.
 *
 * [centroid] is the running mean of every face embedding in the cluster, packed
 * as bytes; it is updated incrementally as new faces are added.
 *
 * [name] is the one piece of face data the user supplies, from the contact
 * picker, and the only one that cannot be regenerated by re-scanning. It is null
 * until a name is chosen. There is no representative face here: the cluster's
 * best face is a pure function of the [PhotoFace] rows, picked at read time.
 */
@Entity
data class Person(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val centroid: ByteArray,
    val faceCount: Int,
    val name: String?,
)

/**
 * A face detected in a library photo. [clusterId] is the [Person] it was
 * grouped into. [embedding] is kept so faces can be re-clustered later without
 * re-scanning the original photo.
 *
 * [left]/[top]/[right]/[bottom] are the detector's box normalised 0..1, and
 * [srcWidth]/[srcHeight] are the dimensions of the bitmap it was measured
 * against. ImageDecoder applies EXIF rotation, so those are *display*
 * orientation — unlike [Photo.width]/[Photo.height], which come from MediaStore
 * un-corrected and are transposed for rotated JPEGs. They are duplicated across
 * a photo's face rows, which is the price of not needing a second table.
 */
@Entity(indices = [Index(value = ["photoId"]), Index(value = ["clusterId"])])
data class PhotoFace(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val photoId: Long,
    val clusterId: Long,
    val embedding: ByteArray,
    val left: Float,
    val top: Float,
    val right: Float,
    val bottom: Float,
    val srcWidth: Int,
    val srcHeight: Int,
)

@Dao
interface FaceDao {
    @Insert
    suspend fun insertPerson(person: Person): Long

    @Update
    suspend fun updatePerson(person: Person)

    @Query("SELECT * FROM Person")
    suspend fun getPersons(): List<Person>

    /** All clusters, for the People view. */
    @Query("SELECT * FROM Person")
    fun personsFlow(): Flow<List<Person>>

    @Query("DELETE FROM Person")
    suspend fun clearPersons()

    @Query("DELETE FROM Person WHERE id = :id")
    suspend fun deletePerson(id: Long)

    /** Name a cluster (or clear its name with null). */
    @Query("UPDATE Person SET name = :name WHERE id = :id")
    suspend fun setPersonName(id: Long, name: String?)

    @Insert
    suspend fun insertPhotoFaces(faces: List<PhotoFace>)

    @Query("DELETE FROM PhotoFace WHERE photoId IN (:photoIds)")
    suspend fun deletePhotoFacesByPhotoIds(photoIds: List<Long>)

    @Query("DELETE FROM PhotoFace")
    suspend fun clearPhotoFaces()

    /** Move every face from one cluster to another (used by the merge pass). */
    @Query("UPDATE PhotoFace SET clusterId = :newId WHERE clusterId = :oldId")
    suspend fun reassignCluster(oldId: Long, newId: Long)

    /** Every detected face, for grouping photos by cluster in the UI. */
    @Query("SELECT * FROM PhotoFace")
    fun allFacesFlow(): Flow<List<PhotoFace>>

    @Query("SELECT DISTINCT photoId FROM PhotoFace WHERE clusterId = :clusterId")
    suspend fun photoIdsForCluster(clusterId: Long): List<Long>
}
