package com.vayunmathur.cast.protocol

import com.vayunmathur.library.util.Hkdf
import java.security.MessageDigest
import java.security.SecureRandom
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec

/**
 * Everything derived from the one 32-byte session secret.
 *
 * The secret is generated by the phone and sealed to the TV's ML-KEM public key, so it is the only
 * thing that crosses the wire; every key below is expanded from it by HKDF-SHA256 with a distinct
 * `info` string. Nothing is ever transmitted, which means a wrong derivation on either side shows up
 * as a black screen rather than as a rejected message - hence the round-trip test asserting the two
 * ends produce identical schedules from the same secret.
 *
 * **No Android or PQC dependency**: this whole file runs on the JVM, which is what makes the pairing
 * rules testable without a TV. Sealing the secret is [SecretSealing]'s job precisely so that the
 * native ML-KEM library stays out of here.
 */
class SessionKeys private constructor(secret: ByteArray) {

    /** AES-256-GCM key for the control channel, from `SEALED_SECRET` onward. */
    val control: ByteArray = derive(secret, "control", CONTROL_KEY_BYTES)

    val audio: StreamKeys = StreamKeys(
        key = derive(secret, "audio key", MEDIA_KEY_BYTES),
        ivMask = derive(secret, "audio iv", MEDIA_KEY_BYTES),
    )

    val video: StreamKeys = StreamKeys(
        key = derive(secret, "video key", MEDIA_KEY_BYTES),
        ivMask = derive(secret, "video iv", MEDIA_KEY_BYTES),
    )

    /** HMAC key for the six-digit pair proof. */
    private val pairKey: ByteArray = derive(secret, "pair", CONTROL_KEY_BYTES)

    /** HMAC key for proving possession of a remembered device key. */
    private val deviceKeyProofKey: ByteArray = derive(secret, "device", CONTROL_KEY_BYTES)

    /**
     * `HMAC(HKDF(secret, "pair"), code ‖ transcript)`.
     *
     * **Binding the code to the transcript is what makes six digits sufficient.** The transcript
     * covers the TV's public bundle, so a man in the middle - which necessarily substituted its own
     * bundle - is proving a transcript it did not create, and cannot. Without that binding, six
     * digits would be six digits of entropy against an attacker who can replay; with it, the code
     * only has to survive the online attempt limit the receiver enforces.
     */
    fun pairProof(code: String, transcript: ByteArray): ByteArray =
        hmac(pairKey, code.toByteArray(Charsets.UTF_8) + transcript)

    /**
     * The same shape for a device the user already paired: possession of [deviceKey] replaces the
     * code, so a second session shows nothing on screen.
     */
    fun deviceProof(deviceKey: ByteArray, transcript: ByteArray): ByteArray =
        hmac(deviceKeyProofKey, deviceKey + transcript)

    companion object {
        const val SECRET_BYTES = 32
        private const val CONTROL_KEY_BYTES = 32
        private const val MEDIA_KEY_BYTES = 16

        /** Namespaced so this secret can never collide with another feature's HKDF output. */
        private const val INFO_PREFIX = "com.vayunmathur.cast/"

        fun of(secret: ByteArray): SessionKeys {
            require(secret.size == SECRET_BYTES) {
                "the session secret is $SECRET_BYTES bytes; got ${secret.size}"
            }
            return SessionKeys(secret)
        }

        /** A fresh session secret. Generated by the phone, once per session. */
        fun newSecret(random: SecureRandom = SecureRandom()): ByteArray =
            ByteArray(SECRET_BYTES).also { random.nextBytes(it) }

        private fun derive(secret: ByteArray, purpose: String, length: Int): ByteArray =
            Hkdf.derive(secret, "$INFO_PREFIX$purpose".toByteArray(Charsets.UTF_8), length)

        private fun hmac(key: ByteArray, data: ByteArray): ByteArray =
            Mac.getInstance("HmacSHA256")
                .apply { init(SecretKeySpec(key, "HmacSHA256")) }
                .doFinal(data)
    }
}

/**
 * The six digits the TV shows and the user types on the phone.
 *
 * Six is enough only because the proof is transcript-bound and the receiver limits attempts - see
 * [SessionKeys.pairProof]. **`SecurityCode.compute` from `:library:e2ee-p2p` is not usable here**:
 * it is 4000 SHA-256 iterations over concatenated key hashes producing a 30-digit *comparison*
 * number for two humans to read to each other. Stretching gives a low-entropy shared secret no
 * protection at all against an online attacker, which is the only attacker this faces.
 */
object PairCode {

    const val DIGITS = 6

    /**
     * How many wrong codes before the displayed one is thrown away.
     *
     * Three, then a new code: this is what removes the offline-guessing objection to six digits, so
     * it is a correctness boundary rather than a nicety.
     */
    const val MAX_ATTEMPTS = 3

    private const val RANGE = 1_000_000

    fun random(random: SecureRandom = SecureRandom()): String =
        random.nextInt(RANGE).toString().padStart(DIGITS, '0')

    /** True when [entered] could be a code at all, so a typo is refused without an HMAC. */
    fun isWellFormed(entered: String): Boolean =
        entered.length == DIGITS && entered.all { it in '0'..'9' }
}

/**
 * The running hash of the handshake, up to and including `SEALED_SECRET`.
 *
 * Fed the **exact bytes that crossed the wire**, not re-encoded objects: JSON round-tripping is not
 * guaranteed to be byte-stable, and a transcript that differs by a key order is a transcript the two
 * ends disagree on - which would fail every pair attempt with no clue as to why.
 */
class Transcript {

    private val bodies = mutableListOf<ByteArray>()

    fun add(body: ByteArray) {
        bodies += body
    }

    fun value(): ByteArray {
        val digest = MessageDigest.getInstance("SHA-256")
        for (body in bodies) digest.update(body)
        return digest.digest()
    }
}

/** Constant-time comparison, so a wrong proof leaks nothing about how wrong it was. */
fun proofsMatch(a: ByteArray, b: ByteArray): Boolean = MessageDigest.isEqual(a, b)
